apiVersion: v1
kind: Service
metadata:
  name: game-2048-svc          # ← starts with letter now
  namespace: game-2048          # ← namespace also can't start with number
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: 2048-game
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP